# Gradle Properties
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Project Details
jvm_version=8

project_group=de.florianreuth
project_name=DietrichEvents2
project_version=1.3.1-SNAPSHOT
project_description=One of the fastest Java event systems in the world using compiler optimizations, which still has a lot of features

publish_owner_id=florianreuth
publish_owner_name=Florian Reuth
publish_owner_mail=git@florianreuth.de
